# Generated by Django 5.2.15 on 2026-06-18 16:29

import chat.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.CharField(default=chat.models.generate_meeting_id, max_length=255, primary_key=True, serialize=False)),
                ('meeting_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('datetime', models.DateTimeField()),
                ('created_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('participants', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
